### ISSUE TITLE
"Couldn't find a tree builder with the features you requested: xml."

### ISSUE THREAD

**Issue by derhuerst** [NoMoKeTo/clifa#8]
I installed *clifa* by `sudo pip install clifa`.

```shell
clifa route düsseldorf hbf essen hbf
```

gives me

```
﻿﻿﻿﻿Traceback (most recent call last):
  File "/usr/local/bin/clifa", line 11, in <module>
    sys.exit(launch())
  File "/usr/local/lib/python2.7/site-packages/clifa_launch.py", line 4, in launch
    import clifa
  File "/usr/local/lib/python2.7/site-packages/clifa.py", line 245, in <module>
    print efa.tripRequest(origin=point_from, destination=point_to, via=point_via, time=time, timetype=timetype, max_interchanges=max_interchanges, select_interchange_by=args.prefer, use_near_stops=args.proximity, train_type=args.include, walk_speed=args.walk_speed, with_bike=args.bike, apitype=args.api)
  File "/usr/local/lib/python2.7/site-packages/pyefa/triprequest.py", line 124, in tripRequest
    result = self.parseTripXML(rawdata, result)
  File "/usr/local/lib/python2.7/site-packages/pyefa/triprequest.py", line 134, in parseTripXML
    soup = BeautifulSoup(xmldata, 'xml')
  File "/usr/local/lib/python2.7/site-packages/bs4/__init__.py", line 156, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: xml. Do you need to install a parser library?
```

**Comment by NoMoKeTo** [comment]
clifa currently no longer maintained because it is based on pyefa which is no longer supported and will be replaced by choo.
